# Generated by Django 2.2.2 on 2019-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20190610_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
